// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAyNqh2jUhERqhfzNYmrPzkjytwVqWOBE',
    appId: '1:615226397677:web:cfe83402dc333541884de4',
    messagingSenderId: '615226397677',
    projectId: 'twitter-clone-recruitchaos',
    authDomain: 'twitter-clone-recruitchaos.firebaseapp.com',
    storageBucket: 'twitter-clone-recruitchaos.appspot.com',
    measurementId: 'G-9YM87CS819',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWOyr08dZjn6fl32wDAJ1FX3-BJZi6BWo',
    appId: '1:615226397677:android:e2b44c020f0f9908884de4',
    messagingSenderId: '615226397677',
    projectId: 'twitter-clone-recruitchaos',
    storageBucket: 'twitter-clone-recruitchaos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-3Mq02K8jgGI2sHCZFfs3Fz36QdOWIMk',
    appId: '1:615226397677:ios:60879ae865ea76ee884de4',
    messagingSenderId: '615226397677',
    projectId: 'twitter-clone-recruitchaos',
    storageBucket: 'twitter-clone-recruitchaos.appspot.com',
    iosClientId: '615226397677-rn1sjm1d9qhp9lms62f9mrb585absuu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-3Mq02K8jgGI2sHCZFfs3Fz36QdOWIMk',
    appId: '1:615226397677:ios:3852e46fc93e5089884de4',
    messagingSenderId: '615226397677',
    projectId: 'twitter-clone-recruitchaos',
    storageBucket: 'twitter-clone-recruitchaos.appspot.com',
    iosClientId: '615226397677-5bfdd26iskhg9p1115vu9cflghhrtnt7.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone.RunnerTests',
  );
}
